// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DebugTraceEntry } from "./DebugTraceEntry";
import type { DebugTraceLane } from "./DebugTraceLane";

export type DebugTraceSnapshot = { schemaVersion: string, conversationId: string, generatedAtUnixSec: bigint, generatedAtRfc3339Sec: string, lanes: Array<DebugTraceLane>, entries: Array<DebugTraceEntry>, };
