// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DebugTraceLanePosition } from "./DebugTraceLanePosition";

export type DebugTraceLane = { agentThreadId: string, agentName: string, laneIndex: bigint, lanePosition: DebugTraceLanePosition, };
