// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DebugTraceAgentKind } from "./DebugTraceAgentKind";
import type { DebugTraceRole } from "./DebugTraceRole";

export type DebugTraceEntry = { conversationId: string, entrySeq: bigint, timestampUnixSec: bigint, timestampRfc3339Sec: string, agentThreadId: string, agentName: string, agentKind: DebugTraceAgentKind, role: DebugTraceRole, sourceEvent: string, content: string, laneIndex?: bigint, };
