// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CollabWaitLifecycleState } from "./CollabWaitLifecycleState";
import type { ThreadId } from "./ThreadId";

export type CollabWaitTargetEvent = { 
/**
 * Receiver thread id.
 */
receiver_thread_id: ThreadId, 
/**
 * Human-readable receiver label. Falls back to receiver thread id when unavailable.
 */
receiver_agent_name: string, 
/**
 * Correlation key expected in callback reply_to_message_id.
 */
message_id: string, 
/**
 * Backend wait lifecycle state for this target.
 */
state: CollabWaitLifecycleState, 
/**
 * Callback payload content for completed targets.
 */
callback_content: string | null, };
