// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CollabWaitTargetEvent } from "./CollabWaitTargetEvent";
import type { ThreadId } from "./ThreadId";

export type CollabWaitingEndEvent = { 
/**
 * Thread ID of the sender.
 */
sender_thread_id: ThreadId, 
/**
 * Human-readable sender label. Falls back to sender thread id when unavailable.
 */
sender_agent_name: string, 
/**
 * ID of the waiting call.
 */
call_id: string, 
/**
 * Whether this wait call timed out with at least one unsatisfied target.
 */
timed_out: boolean, 
/**
 * Wait targets tracked by this call.
 */
targets: Array<CollabWaitTargetEvent>, };
