// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ThreadId } from "./ThreadId";

export type CollabAgentSpawnBeginEvent = { 
/**
 * Identifier for the collab tool call.
 */
call_id: string, 
/**
 * Thread ID of the sender.
 */
sender_thread_id: ThreadId, 
/**
 * Agent-specific system prompt configured at spawn time. Empty when omitted.
 */
prompt: string, };
