// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DebugTraceLanePosition } from "./DebugTraceLanePosition";
import type { ThreadId } from "./ThreadId";

export type DebugTraceLane = { agent_thread_id: ThreadId, agent_name: string, lane_index: bigint, lane_position: DebugTraceLanePosition, };
