// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DebugTraceAgentKind } from "./DebugTraceAgentKind";
import type { DebugTraceRole } from "./DebugTraceRole";
import type { ThreadId } from "./ThreadId";

export type DebugTraceEntry = { conversation_id: ThreadId, entry_seq: bigint, timestamp_unix_sec: bigint, timestamp_rfc3339_sec: string, agent_thread_id: ThreadId, agent_name: string, agent_kind: DebugTraceAgentKind, role: DebugTraceRole, source_event: string, content: string, lane_index?: bigint | null, };
